### ISSUE TITLE
Basinex has issues on EVE

### ISSUE THREAD

**Issue by pallavhydro** [mhm-ufz/basinex#11]
Basinex has some issue on EVE. Running the example case throws the error messages as shown in the screenshot below. 

Tagging @MuellerSeb and @StephanThober 

<img width="1502" alt="Screenshot 2024-01-15 at 23 25 15" src="https://github.com/mhm-ufz/basinex/assets/58865333/70f7782a-2271-4522-855b-2b79c56a61c5">

p.s. The problem persists while testing @lotruheawea 's fork as well.

**Comment by lotruheawea** [comment]
yes, this is due to an updated numpy version that does not support np.bool anymore. An easy fix is the replacement of all its occurences by bool as indicated in the error message. Alternatively, switch to an older version of numpy.

**Comment by pallavhydro** [comment]
I followed the `readme.md` and did the following:

```
conda install -y gdal netcdf4 pyyaml cxx-compiler
pip install .
```

Now I should specify the version of python or numpy in the `conda install` command, right? Something like this (??)

```
conda install -y gdal netcdf4 pyyaml cxx-compiler python=3.10
```

**Comment by pallavhydro** [comment]
Ok, the solution is the following `conda install` command (courtesy: @MuellerSeb). 

```
conda install python=3.10 "numpy<1.23" "netcdf4<1.6" gdal pyyaml cxx-compiler
```

Might be worth updating the `Readme.md` with the above and a note on the versions.

Thanks @lotruheawea for your hints 👍
